name: Sync open-cad-studio

on:
  schedule:
    - cron: '53 4 * * *'
  workflow_dispatch:

jobs:
  sync:
    uses: tubbywrestler/aur-bin-chicken/.github/workflows/sync-and-build.yml@master
    with:
      aur_pkgbase: open-cad-studio
    permissions:
      contents: write
